Prep for Azure Trusted Signing

diff --git a/.github/workflows/build_viewer.yml b/.github/workflows/build_viewer.yml
--- a/.github/workflows/build_viewer.yml
+++ b/.github/workflows/build_viewer.yml
@@ -302,6 +302,68 @@ jobs:
           autobuild configure -c ReleaseFS -A${addrsize} -- --package --chan ${{env.FS_RELEASE_CHAN}} ${{env.EXTRA_ARGS}} ${{env.FS_GRID}}
           echo "BUGSPLAT_DB=$BUGSPLAT_DB" >> $GITHUB_ENV
         shell: bash
+      - name: Setup env for code signing on windows
+        if: runner.os == 'Windows'
+        run: |
+          echo "FS_CERT=${{ secrets.FS_CERT }}" >> $GITHUB_ENV
+          echo "FS_CERT_PASS=${{ secrets.FS_CERT_PASS }}" >> $GITHUB_ENV
+      - name: Generate metadata.json
+        run: |
+          echo '{
+          "Endpoint": "${{ secrets.AZURE_ENDPOINT }}",
+          "CodeSigningAccountName": "${{ secrets.AZURE_CODE_SIGNING_NAME }}",
+          "CertificateProfileName": "${{ secrets.AZURE_CERT_PROFILE_NAME }}",
+          "ExcludeCredentials": [
+            "ManagedIdentityCredential"
+          ]
+          }' > ${{github.workspace}}/metadata.json
+      - name: Prime the env for trusted code support
+        if: runner.os == 'Windows'
+        run: |
+          echo "AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
+          echo "AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV
+          echo "AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
+          echo "CODESIGNING_METADATA_PATH=${{github.workspace}}/metadata.json" >> $GITHUB_ENV
+          - name: Validate Windows 10 SDK version and find signtool.exe
+      - name: locate signtool
+        if: runner.os == 'Windows'
+        id: validate-sdk
+        run: |
+          $sdkPath = (Get-ChildItem "C:\Program Files (x86)\Windows Kits\10\bin" -Recurse -Directory | Sort-Object Name -Descending | Select-Object -First 1).FullName
+          if (-not $sdkPath) {
+            Write-Error "Required Windows 10 SDK version not installed."
+            exit 1
+          }
+          $signtoolPath = Join-Path $sdkPath "x64\signtool.exe"
+          if (-not (Test-Path $signtoolPath)) {
+            Write-Error "signtool.exe not found in the SDK path."
+            exit 1
+          }
+          echo "SIGNSDK_PATH=$sdkPath" >> $env:GITHUB_ENV
+          echo "SIGNTOOL_PATH=$signtoolPath" >> $env:GITHUB_ENV
+        shell: pwsh          
+      - name: Install nuget.exe
+        if: runner.os == 'Windows'
+        run: |
+          Invoke-WebRequest -Uri https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -OutFile nuget.exe
+        shell: pwsh
+
+      - name: Install Microsoft.Trusted.Signing.Client
+        if: runner.os == 'Windows'
+        run: |
+          .\nuget.exe install Microsoft.Trusted.Signing.Client -Version 1.0.53 -OutputDirectory .
+        shell: pwsh
+
+      - name: Locate Azure.CodeSigning.Dlib.dll
+        if: runner.os == 'Windows'
+        run: |
+          $dllPath = (Get-ChildItem ".\Microsoft.Trusted.Signing.Client.1.0.53\bin\x64\Azure.CodeSigning.Dlib.dll" -Recurse -File | Select-Object -First 1).FullName
+          if (-not $dllPath) {
+            Write-Error "Azure.CodeSigning.Dlib.dll not found."
+            exit 1
+          }
+          echo "CODESIGNING_DLIB_PATH=$dllPath" >> $env:GITHUB_ENV
+        shell: pwsh
       - name: build
         id: build
         run: autobuild build -c ReleaseFS -A${addrsize} --no-configure
